### ISSUE TITLE
Missing install instruction

### ISSUE THREAD

**Issue by m42smith** [ctesta01/QualtricsTools#47]
Hi, 
to be able to install QualtricsTool I need to execute: 

devtools::install_github('wleepang/shiny-directory-input')

before I can execute: 

devtools::install_github("ctesta01/QualtricsTools")

Maybe you can add that to the tutorial. 

Thanks

**Comment by emma-morgan** [comment]
Hello,

This is no longer the active branch of QualtricsTools. Please visit emma-morgan/QualtricsTools for the version of this package that is being maintained. You will see instructions for installing the referenced dependency in the home page of the wiki.

https://github.com/emma-morgan/QualtricsTools/wiki#installing-and-running-the-shiny-app
